version: '3.8'

services:
  db:
    image: postgres:14
    container_name: pg-docker
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    restart: always

volumes:
    dbdata:
        name: pg-dbdata
