logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/dev

info:
  application:
    name: spring-demo
    description: A blog with articles about The Spring Framework
    author: Antanas A.
    version: '0.1'